version: "3.4"

services:
  friendchise:
    container_name: friendchise
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
        - friendchise_network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
        - friendchise_network

networks:
  friendchise_network: